/**
 * NOTARYGO™ — Notary Office Operational Control System
 * Role-Based Access Control (RBAC) & Permission Matrix
 */

var Permissions = (function() {
  var PERMISSIONS = {
    // Matters
    MATTER_VIEW_ALL: 'MATTER_VIEW_ALL',
    MATTER_VIEW_ASSIGNED: 'MATTER_VIEW_ASSIGNED',
    MATTER_CREATE: 'MATTER_CREATE',
    MATTER_EDIT: 'MATTER_EDIT',
    MATTER_CANCEL: 'MATTER_CANCEL',
    MATTER_ARCHIVE: 'MATTER_ARCHIVE',
    MATTER_RESTORE: 'MATTER_RESTORE',
    MATTER_OVERRIDE_WORKFLOW: 'MATTER_OVERRIDE_WORKFLOW',

    // Tasks & Operations
    TASK_MANAGE_ALL: 'TASK_MANAGE_ALL',
    TASK_UPDATE_ASSIGNED: 'TASK_UPDATE_ASSIGNED',
    PENDING_MANAGE: 'PENDING_MANAGE',
    FOLLOW_UP_MANAGE: 'FOLLOW_UP_MANAGE',
    CHECKLIST_VERIFY: 'CHECKLIST_VERIFY',
    SIGNING_MANAGE: 'SIGNING_MANAGE',
    APPROVAL_REVIEW: 'APPROVAL_REVIEW',

    // Clients & Organizations
    CLIENT_MANAGE: 'CLIENT_MANAGE',
    ORGANIZATION_MANAGE: 'ORGANIZATION_MANAGE',

    // Documents & PDFs
    DOCUMENT_VIEW_ALL: 'DOCUMENT_VIEW_ALL',
    DOCUMENT_UPLOAD: 'DOCUMENT_UPLOAD',
    DOCUMENT_GENERATE_PDF: 'DOCUMENT_GENERATE_PDF',

    // Finance & Invoicing
    FINANCE_VIEW_ALL: 'FINANCE_VIEW_ALL',
    FINANCE_MANAGE_INVOICE: 'FINANCE_MANAGE_INVOICE',
    FINANCE_RECORD_PAYMENT: 'FINANCE_RECORD_PAYMENT',

    // Control & Management
    DASHBOARD_OWNER: 'DASHBOARD_OWNER',
    REPORTS_VIEW_ALL: 'REPORTS_VIEW_ALL',
    REPORTS_VIEW_OPERATIONAL: 'REPORTS_VIEW_OPERATIONAL',
    AUDIT_LOG_VIEW: 'AUDIT_LOG_VIEW',
    HANDOVER_STAFF: 'HANDOVER_STAFF',

    // System & Settings
    SYSTEM_MANAGE_USERS: 'SYSTEM_MANAGE_USERS',
    SYSTEM_MANAGE_OFFICE: 'SYSTEM_MANAGE_OFFICE',
    SYSTEM_MANAGE_WORKFLOWS: 'SYSTEM_MANAGE_WORKFLOWS',
    SYSTEM_MANAGE_BACKUP: 'SYSTEM_MANAGE_BACKUP',
    SYSTEM_HEALTH_CHECK: 'SYSTEM_HEALTH_CHECK'
  };

  var ROLE_MATRIX = {};

  ROLE_MATRIX[CONFIG.ROLES.OWNER] = [
    PERMISSIONS.MATTER_VIEW_ALL,
    PERMISSIONS.MATTER_CREATE,
    PERMISSIONS.MATTER_EDIT,
    PERMISSIONS.MATTER_CANCEL,
    PERMISSIONS.MATTER_ARCHIVE,
    PERMISSIONS.MATTER_RESTORE,
    PERMISSIONS.MATTER_OVERRIDE_WORKFLOW,
    PERMISSIONS.TASK_MANAGE_ALL,
    PERMISSIONS.TASK_UPDATE_ASSIGNED,
    PERMISSIONS.PENDING_MANAGE,
    PERMISSIONS.FOLLOW_UP_MANAGE,
    PERMISSIONS.CHECKLIST_VERIFY,
    PERMISSIONS.SIGNING_MANAGE,
    PERMISSIONS.APPROVAL_REVIEW,
    PERMISSIONS.CLIENT_MANAGE,
    PERMISSIONS.ORGANIZATION_MANAGE,
    PERMISSIONS.DOCUMENT_VIEW_ALL,
    PERMISSIONS.DOCUMENT_UPLOAD,
    PERMISSIONS.DOCUMENT_GENERATE_PDF,
    PERMISSIONS.FINANCE_VIEW_ALL,
    PERMISSIONS.FINANCE_MANAGE_INVOICE,
    PERMISSIONS.FINANCE_RECORD_PAYMENT,
    PERMISSIONS.DASHBOARD_OWNER,
    PERMISSIONS.REPORTS_VIEW_ALL,
    PERMISSIONS.REPORTS_VIEW_OPERATIONAL,
    PERMISSIONS.AUDIT_LOG_VIEW,
    PERMISSIONS.HANDOVER_STAFF,
    PERMISSIONS.SYSTEM_MANAGE_USERS,
    PERMISSIONS.SYSTEM_MANAGE_OFFICE,
    PERMISSIONS.SYSTEM_MANAGE_WORKFLOWS,
    PERMISSIONS.SYSTEM_MANAGE_BACKUP,
    PERMISSIONS.SYSTEM_HEALTH_CHECK
  ];

  ROLE_MATRIX[CONFIG.ROLES.ADMIN] = [
    PERMISSIONS.MATTER_VIEW_ALL,
    PERMISSIONS.MATTER_CREATE,
    PERMISSIONS.MATTER_EDIT,
    PERMISSIONS.MATTER_CANCEL,
    PERMISSIONS.MATTER_ARCHIVE,
    PERMISSIONS.TASK_MANAGE_ALL,
    PERMISSIONS.TASK_UPDATE_ASSIGNED,
    PERMISSIONS.PENDING_MANAGE,
    PERMISSIONS.FOLLOW_UP_MANAGE,
    PERMISSIONS.CHECKLIST_VERIFY,
    PERMISSIONS.SIGNING_MANAGE,
    PERMISSIONS.APPROVAL_REVIEW,
    PERMISSIONS.CLIENT_MANAGE,
    PERMISSIONS.ORGANIZATION_MANAGE,
    PERMISSIONS.DOCUMENT_VIEW_ALL,
    PERMISSIONS.DOCUMENT_UPLOAD,
    PERMISSIONS.DOCUMENT_GENERATE_PDF,
    PERMISSIONS.FINANCE_VIEW_ALL,
    PERMISSIONS.FINANCE_MANAGE_INVOICE,
    PERMISSIONS.FINANCE_RECORD_PAYMENT,
    PERMISSIONS.DASHBOARD_OWNER,
    PERMISSIONS.REPORTS_VIEW_OPERATIONAL,
    PERMISSIONS.HANDOVER_STAFF,
    PERMISSIONS.SYSTEM_HEALTH_CHECK
  ];

  ROLE_MATRIX[CONFIG.ROLES.SUPERVISOR] = [
    PERMISSIONS.MATTER_VIEW_ALL,
    PERMISSIONS.MATTER_EDIT,
    PERMISSIONS.TASK_MANAGE_ALL,
    PERMISSIONS.TASK_UPDATE_ASSIGNED,
    PERMISSIONS.PENDING_MANAGE,
    PERMISSIONS.FOLLOW_UP_MANAGE,
    PERMISSIONS.CHECKLIST_VERIFY,
    PERMISSIONS.SIGNING_MANAGE,
    PERMISSIONS.APPROVAL_REVIEW,
    PERMISSIONS.CLIENT_MANAGE,
    PERMISSIONS.DOCUMENT_VIEW_ALL,
    PERMISSIONS.DOCUMENT_UPLOAD,
    PERMISSIONS.DOCUMENT_GENERATE_PDF,
    PERMISSIONS.REPORTS_VIEW_OPERATIONAL
  ];

  ROLE_MATRIX[CONFIG.ROLES.STAFF] = [
    PERMISSIONS.MATTER_VIEW_ASSIGNED,
    PERMISSIONS.TASK_UPDATE_ASSIGNED,
    PERMISSIONS.FOLLOW_UP_MANAGE,
    PERMISSIONS.CHECKLIST_VERIFY,
    PERMISSIONS.DOCUMENT_UPLOAD,
    PERMISSIONS.DOCUMENT_GENERATE_PDF
  ];

  ROLE_MATRIX[CONFIG.ROLES.FINANCE] = [
    PERMISSIONS.MATTER_VIEW_ALL,
    PERMISSIONS.FINANCE_VIEW_ALL,
    PERMISSIONS.FINANCE_MANAGE_INVOICE,
    PERMISSIONS.FINANCE_RECORD_PAYMENT,
    PERMISSIONS.DOCUMENT_GENERATE_PDF,
    PERMISSIONS.REPORTS_VIEW_ALL
  ];

  /**
   * Checks whether a role has a specific permission
   * @param {string} role
   * @param {string} permission
   * @return {boolean}
   */
  function hasPermission(role, permission) {
    if (!role) return false;
    var allowed = ROLE_MATRIX[role];
    return allowed ? allowed.indexOf(permission) !== -1 : false;
  }

  return {
    LIST: PERMISSIONS,
    MATRIX: ROLE_MATRIX,
    hasPermission: hasPermission
  };
})();
